import NextAuthSessionProvider from "@/lib/session-provider";
import "./globals.css";
import "./editor.css";
import { ThemeProvider } from "next-themes";
import localFont from "next/font/local";

const inter = localFont({
  src: "./font/InterVariable.ttf",
  display: "swap",
});
export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className}`}>
      <body className="h-screen w-full overflow-hidden bg-neutral-100 dark:bg-neutral-900">
        <ThemeProvider attribute="class">
          <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
